wpplot <- function(ID) {
    url <- paste0('https://www.wikipathways.org//wpi/wpi.php?action=',
            'downloadFile&type=svg&pwTitle=Pathway:',
            ID)
    svg <- readLines(url)
    if (!any(grepl('<svg', svg[1:10]))) {
        stop("fail to read online wiki pathway file")
    }
    structure(list(
        ID = ID, 
        svg = svg,
        geneExpr = NULL
    ), class = "wpplot")    
}


wp_bgfill <- function(p, value, low="blue", high="red", legend = TRUE) {
  # node number
  n <- length(value)

  mini <- min(value) %/% 10 * 10
  maxi <- ceiling(max(value)/10) * 10
  colornum <- (maxi-mini) / 10

  colorbar <- colorb(value, low, high)
  color <- colorbar[order(Expression)]

  genes <- names(value)

  for (i in seq_along(genes)) {
    pos <- grep(genes[i], p$svg)
    p$svg <- replace_bg2(p$svg, pos, color[i])
  }


  rectY<-seq(from = 50,by = 20,length.out = colornum)
  rectY<-rev(rectY) 
  textY<-seq(from = 53,by = 20,length.out = colornum+1)

  textele<-seq(from = maxi,to = mini,by = -10)

    if (legend) {
        for (i in 1:colornum) {
            temp<-grep("></svg",p$svg)
            p$svg[temp]<-sub("</svg",paste("><rect x=\"30\" y=\"",rectY[i],"\" width=\"30\" height=\"20\" style=\"fill:",colorbar[i],"\"/></svg",sep = ""),p$svg[temp])
        }

        for (i in 1:(colornum+1)) {
            temp<-grep("></svg",p$svg)
            p$svg[temp]<-sub("</svg",paste("<text x=\"70\" y=\"",textY[i],"\" style=\"font-size:10; fill:black; stroke:none\">",textele[i],"</text></svg",sep = ""),p$svg[temp])
        }
    }
    p$geneExpr <- value
  return(p)
}

wp_shadowtext <- function(p, bg.r = 2, bg.col = "white") {
    if (is.null(p$geneExpr)) return(p)

  genes <- names(p$geneExpr)

  for (i in seq_along(genes)) {
    pos <- grep(genes[i], p$svg)
    p$svg <- svg_halos(p$svg, pos, genes[i])
  }

   i <- grep("><!--Generated by the Batik Graphics2D SVG Generator-->", p$svg)

  p$svg[i] <- paste0(
    "><!--Generated by the Batik Graphics2D SVG Generator-->", 
    "<style>.halo{fill:", bg.col, 
    ";stroke:", bg.col, "; stroke-width:", bg.r, 
    ";stroke-linejoin:round; vector-effect:non-scaling-stroke;",
    "}</style><defs id=\"genericDefs\""
  )

    return(p)
}


wpsave <- function(p, file, width=NULL, height=NULL) {
    fileext <- sub(".*(\\..+)", "\\1", file)
    f <- svg2tempfile(p$svg)
    if (fileext == 'svg') {
        rsvg::rsvg_svg(f, file = file, width = width, height = height)
    } else if (fileext == 'pdf') {
        rsvg::rsvg_pdf(f, file = file, width = width, height = height)
    } else if (fileext == 'png') {
        rsvg::rsvg_png(f, file = file, width = width, height = height)
    } else {
        stop("file type not supported")
    }

    invisible(p)
}



