#' @title Input specific wikipathways ID to get an output in class of wpplot.
#' @description Use wikipathways ID to open a local svg file. Then extract related information from svg file and build a wpplot class variance.
#' @param ID ID is wikipathways' ID.
#' @export

wpplot <- function(ID) {   #数据预处理
  url <- paste0('https://www.wikipathways.org//wpi/wpi.php?action=',
                'downloadFile&type=svg&pwTitle=Pathway:',
                ID)  #获得特定ID的通路图的svg文件
  svg <- readLines(url)  #逐行读入
  if (!any(grepl('<svg', svg[1:10]))) {  #如果文件前十行没有内容，则返回读取失败
    stop("fail to read online wiki pathway file")
  }
  structure(list(  #返回一个类为wpplot的对象吗？wpplot是什么类？
    ID = ID,
    svg = svg,
    geneExpr = NULL
  ), class = "wpplot")
}

#' @title Fill the background of gene with color according to amount of gene expression.
#' @description Generate a color array.Fill the gene then generate the legend.
#' @param p p is
#' @param value value is the amount of expression.
#' @param low The color of lowest gene.
#' @param high The color of highest gene.
#' @param legend Whether you need legend.
#' @export

wp_bgfill <- function(p, value, low="blue", high="red", legend = TRUE) { #填充背景颜色和legend
  # node number
  n <- length(value)    #节点的个数。value是储存表达量的向量。

  mini <- min(value) %/% 10 * 10  #计算表达量下界
  maxi <- ceiling(max(value)/10) * 10 #计算表达量上界
  colornum <- (maxi-mini) / 10 #计算需要多少种颜色（每10一变色）

  colorbar <- colorb(value, low, high)  #生成颜色序列
  color <- colorbar[order(value)]   #(Expression->value)把每个表达量对应的颜色存入color

  genes <- names(value)  #取基因名

  for (i in seq_along(genes)) { #循环基因个数次
    pos <- grep(genes[i], p$svg)  #将基因名所在的行存入pos
    p$svg <- replace_bg2(p$svg, pos, color[i])  #改变它的背景颜色
  }


  rectY<-seq(from = 50,by = 20,length.out = colornum)   #确定legend的Y坐标们
  rectY<-rev(rectY)   #反向输出rectY，这样才符合svg文件的坐标轴。
  textY<-seq(from = 53,by = 20,length.out = colornum+1) #生成legend上刻度的Y坐标们

  textele<-seq(from = maxi,to = mini,by = -10)  #生成坐标刻度的文本内容

  if (legend) {  #如果legend参数为1
    for (i in 1:colornum) {
      temp<-grep("></svg",p$svg) #取出文档末尾那句话，把p中的svg元素的最后一句替换，加上legend
      p$svg[temp]<-sub("</svg",paste("><rect x=\"30\" y=\"",rectY[i],"\" width=\"30\" height=\"20\" style=\"fill:",colorbar[i],"\"/></svg",sep = ""),p$svg[temp])
    }

    for (i in 1:(colornum+1)) {  #加legend刻度
      temp<-grep("></svg",p$svg)
      p$svg[temp]<-sub("</svg",paste("<text x=\"70\" y=\"",textY[i],"\" style=\"font-size:10; fill:black; stroke:none\">",textele[i],"</text></svg",sep = ""),p$svg[temp])
    }
  }
  p$geneExpr <- value  #把表达量存进Expr
  return(p)
}


#' @title Add halo above gene name to get a clear view.
#' @description Add use svghalo2 function to add halo.
#' @param p An wpplot class variance.
#' @param bg.r The width of halo.
#' @param bg.col The color of halo.
#' @export

wp_shadowtext <- function(p, bg.r = 2, bg.col = "white") { #加halo函数
  if (is.null(p$geneExpr)) return(p)

  genes <- names(p$geneExpr)

  for (i in seq_along(genes)) {
    pos <- grep(genes[i], p$svg)
    p$svg <- svg_halos(p$ svg, pos, genes[i])
  }

  i <- grep("><!--Generated by the Batik Graphics2D SVG Generator-->", p$svg) #找到在第几行

  p$svg[i] <- paste0(
    "><!--Generated by the Batik Graphics2D SVG Generator-->",
    "<style>.halo{fill:", bg.col,
    ";stroke:", bg.col, "; stroke-width:", bg.r,
    ";stroke-linejoin:round; vector-effect:non-scaling-stroke;",
    "}</style><defs id=\"genericDefs\""
  )

  return(p)
}

#' @title Save svg picture in specific address.
#' @import rsvg
#' @param p A wpplot class variance.
#' @param file Address where you want to save the svg.
#' @param width Width of svg.
#' @param height Height of svg.
#' @export

wpsave <- function(p, file, width=NULL, height=NULL) {
  fileext <- sub(".*(\\..+)", "\\1", file)
  f <- svg2tempfile(p$svg) #把svg存入名字为f的文件中
  if (fileext == 'svg') {
    rsvg::rsvg_svg(f, file = file, width = width, height = height) #双冒号临时加载包
  } else if (fileext == 'pdf') {
    rsvg::rsvg_pdf(f, file = file, width = width, height = height)
  } else if (fileext == 'png') {
    rsvg::rsvg_png(f, file = file, width = width, height = height)
  } else {
    stop("file type not supported")
  }

  invisible(p)
}
